= Kenan Kartal

Welcome to my personal website!
I will note down my personal projects, studies and thoughts here.

== Studies

OpenGL Demo (2023):: Forward & deferred rendering demo in OpenGL. link:https://github.com/kenan-kartal/opengl-demo[Repo].
Vulkan Demo (2023):: Demo for precise GPU programming in Vulkan. link:https://github.com/kenan-kartal/vulkan-demo[Repo].
Ray Tracer (2022):: METU graduate course study of advanced ray tracing techniques. link:studies/ray-tracer.html[Index].

== Other

AT&T Ray Seyfarth's Assembly (2024):: AT&T syntax implementation of Ray Seyfarfath's _Introduction to 64 Bit Intel Assembly Language Programming for Linux_ (2011).
	link:https://github.com/kenan-kartal/att-ray-seyfarth[Repo].
Shenzhen I/O - B8ZS (2023):: A custom puzzle in Shenzhen I/O to implement a bipolar with eight zero substitution scrambler. link:other/shenzhen-io-b8zs.html[Post].
Shenzhen I/O - Endless Runner (2023):: An endless runner game implemented in Shenzhen I/O. link:other/shenzhen-io-endless-runner.html[Post].

